import React from 'react';
import { Helmet } from 'react-helmet-async';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

export default function TermsAndConditions() {
  return (
    <div>
      <Helmet>
        <title>Terms and Conditions | Fences Texas</title>
        <meta name="description" content="Terms and Conditions for Fences Texas" />
      </Helmet>
      
      <Navbar />
      
      <main className="container mx-auto px-4 py-8">
        <h1 className="text-4xl font-bold mb-8">Terms and Conditions</h1>
        <div className="prose max-w-none">
          <p>Last Updated: March 27, 2025</p>
          
          <p>Thank you for visiting the FencesTexas™ website located at FencesTexas.com (the "Site"). The Site is an Internet property of Consumer AI ("Company," "we," "our" or "us"). Each end-user visitor to the Site ("User," "you" or "your") agrees to the FencesTexas™ Website Terms and Conditions ("Terms and Conditions"), in their entirety, when she/he: (a) accesses or uses the Site; (b) accesses and/or views any of the: (i) links ("Third-Party Links") to resources and/or information pertaining to fence installation, repairs, and other fence-related services, as well as related products and/or services (collectively, "Fence Services"); and/or (ii) text, video and/or other information pertaining to the Fence Services, as well as related products and/or services, as made available on the Site (the "Informational Content," and together with the Third-Party Links, the "Content"); (c) accesses links to Company's social media pages/accounts featured on third-party social media websites, such as Facebook®, (collectively, "Social Media Pages"); and/or (d) utilizes the various contact forms and/or contact information made available on the Site as a means to contact directly, or request to be contacted by, Company and/or fencing contractors associated with the Fence Services specified by you in connection with the contact form (collectively, the "Third-Party Fencing Contractors") (collectively, the "Contact Services," and together with the Site, Content and Social Media Pages, the "Site Offerings").</p>

          <p className="mt-4">The following Terms and Conditions are inclusive of the FencesTexas™ Privacy Policy ("Privacy Policy") and any and all other applicable operating rules, policies, price schedules and other supplemental terms and conditions or documents that may be published from time to time, which are expressly incorporated herein by reference (collectively, the "Agreement"). By using and/or accessing the Site Offerings, Users agree to comply with and be bound by the Agreement in its entirety.</p>

          <p className="mt-4 font-bold">PLEASE REVIEW THE TERMS OF THE AGREEMENT CAREFULLY. IF A USER DOES NOT AGREE WITH THE TERMS OF THE AGREEMENT IN THEIR ENTIRETY, THAT USER IS NOT AUTHORIZED TO USE THE SITE OFFERINGS IN ANY MANNER OR FORM. THE AGREEMENT CONTAINS DISCLAIMERS OF WARRANTIES, LIMITATIONS OF LIABILITY, RELEASES, A CLASS-ACTION WAIVER, AND THE REQUIREMENT TO ARBITRATE ANY AND ALL CLAIMS THAT MAY ARISE HEREUNDER. THE AFOREMENTIONED PROVISIONS ARE AN ESSENTIAL BASIS OF THE AGREEMENT.</p>

          <p className="mt-4">Please be advised that Company is not a fencing contractor or a fencing contractor referral service. As such, Company offers no fence installation advice, recommendations, or counseling in connection with any Fence Service, under any circumstances, and nothing we do and no element of the Site Offerings should be construed as such. Without limiting the generality of the foregoing, Company does not itself provide fence-related products and/or services in connection with any Fence Service, and the ultimate terms and conditions of any fence-related products and/or services made available via the Contact Services, or otherwise by and through the Site Offerings, shall be determined by the applicable Third-Party Fencing Contractor.</p>

          <p className="mt-4">Any use of the Site Offerings by you, including information submitted by you to Company, is not intended to, and will not create, a contractor-client relationship between you and Company or any of the Third-Party Fencing Contractors. The Site Offerings are not a substitute for professional fence installation and/or financial advice. You should always check with your contractor, accountant and/or other services providers to be sure that any advice, products and/or services offered by and/or through the Site Offerings are appropriate for you. Reliance on any information made available to you by and through the Site Offerings, including the Content, is solely at your own risk. Company disclaims any and all liability for any loss, damage or injury based on information directly or indirectly obtained through the Site Offerings.</p>

          <p className="mt-4">Facebook® is a registered trademark of Meta Platforms, Inc. ("Meta"). Google+ is a registered trademark of Google, Inc. ("Google"). Pinterest® is a registered trademark of Pinterest, Inc. ("Pinterest"). Twitter® is a registered trademark of Twitter, Inc. ("Twitter"). Please be advised that Company is not in any way affiliated with Meta, Google, Pinterest or Twitter, nor are the Site Offerings endorsed, administered or sponsored by any of the foregoing entities.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Scope; Modification of Agreement</h2>
          <p>The Agreement constitutes the entire and only agreement between Users and Company with respect to Users' use of the Site Offerings, and supersedes all prior or contemporaneous agreements, representations, warranties and/or understandings with respect to same. Company may amend the Agreement from time to time in its sole discretion, without specific notice to Users; provided, however, that any amendment or modification to the arbitration provisions, prohibition on class action provisions or any other provisions applicable to dispute resolution (collectively, "Dispute Resolution Provisions") shall not apply to any disputes incurred prior to the applicable amendment or modification. The latest Agreement will be posted on the Site, and Users should review the Agreement prior to using any Site Offerings. By a User's continued use of the Site Offerings, that User hereby agrees to comply with all of the terms and conditions contained within the Agreement effective at that time (other than with respect to disputes arising prior to the amendment or modification of the Dispute Resolution Provisions, which shall be governed by the Dispute Resolution Provisions then in effect at the time of the subject dispute).</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Requirements; Termination of Access to the Site Offerings</h2>
          <p>The Site Offerings are available only to individuals who: (a) are eighteen (18) years of age (or the applicable age of majority, if greater than eighteen (18) years of age in their jurisdiction of residence) or older; and (b) can enter into legally binding contracts under applicable law. If a User is under eighteen (18) years of age (or the applicable age of majority, if greater than eighteen (18) years of age in her/his jurisdiction of residence) and/or if that User is unable to enter into legally binding contracts under applicable law, that User does not have permission to use and/or access the Site Offerings.</p>

          <p className="mt-4">Company may terminate a User's access to the Site Offerings at any time and for any reason, in its sole discretion. Such reasons may include, without limitation, where Company believes that such User is: (i) in any way in breach of the Agreement; and/or (ii) engaged in any improper conduct in connection with the Site Offerings.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Contact Services; Third-Party Service Providers</h2>
          <p>Where a User attempts to utilize the Contact Services, that User may be required to submit, and Company may collect, some or all of the following information: (a) the User's full name; (b) the User's e-mail address; (c) the User's telephone number; (d) the User's zip code; (e) details about the fence project that the User is inquiring about (e.g. type of fence, measurements, timeline, etc.); and (f) any other information requested on the applicable form (collectively, the "User Data").</p>

          <p className="mt-4">Upon entering User Data and clicking on the applicable submission button on the Site, Company may pass your User Data along to one (1) or more of its Third-Party Fencing Contractors. Each User agrees to provide true, accurate, current and complete User Data. Company's use of User Data shall be governed by the Privacy Policy. For a copy of the Privacy Policy, please <a href="/privacy-policy" className="text-blue-600 hover:underline">click here</a>.</p>

          <p className="mt-4">Company does not itself provide fence-related products and/or services in connection with any Fence Service, and the ultimate terms and conditions of any fence-related products and/or services made available via the Contact Services, or otherwise by and through the Site Offerings, shall be determined by the applicable Third-Party Fencing Contractor. <span className="font-bold">YOU UNDERSTAND AND AGREE THAT COMPANY SHALL NOT BE LIABLE TO YOU OR ANY THIRD-PARTY FOR ANY PRODUCTS AND/OR SERVICES OFFERED BY ANY THIRD-PARTY FENCING CONTRACTOR.</span></p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Fence-Related Disclosures; Non-Endorsement; Passive Conduit</h2>
          <p>Company is not a fencing contractor or a fencing contractor referral service. As such, Company offers no fence installation advice, recommendations, or counseling in connection with any Fence Service, under any circumstances, and nothing we do, and no element of the Site Offerings, should be construed as such. Please use caution and common sense when using the Site Offerings. Company in no way endorses the content or legality of any responses, statements or promises made by Third-Party Fencing Contractors or any other parties featured on the Site or otherwise through the Site Offerings. You should always check with your contractor, accountant and/or other advisors to be sure that any advice, products and/or services offered by and/or through the Site Offerings are appropriate for you.</p>

          <p className="mt-4">Some of the Third-Party Fencing Contractors who are accessible by and through the Contact Services pay a fee for inclusion in the Contact Services; provided, however, that Company does not receive any portion of any Third-Party Fencing Contractor's fees beyond the lead generation payment.</p>

          <p className="mt-4">Any use of the Site Offerings by Users is not intended to, and will not create, a contractor-client relationship between any such Users and Company. Without limiting the foregoing, any information submitted to Company and/or any electronic or other communication sent to Company will not create, or be covered by, a contractor-client relationship between Users and Company.</p>

          <p className="mt-4">The Site Offerings facilitate communication between Third-Party Fencing Contractors and potential users of associated fence-related products and/or services. Company does not guarantee that Users will successfully find fence installation representation through the Site Offerings. The determination of the need for fence services and the choice of fencing contractor are important decisions and should not be based solely on advertisements, claims of expertise or cost offered by any Third-Party Fencing Contractor.</p>

          <p className="mt-4">Company does not review the standing of any Third-Party Fencing Contractors with any regulatory authority or contractors' licensing board. Therefore, Company makes no representation regarding the status, standing or ability of any Third-Party Fencing Contractor. When considering retaining a Third-Party Fencing Contractor, Users should ask for free background information from that Third-Party Fencing Contractor and check that Third-Party Fencing Contractor's standing with the applicable state contractors' licensing board. Company is not responsible for, and in no way endorses, any description or indication of specialization or limitation of practice by any Third-Party Fencing Contractors that are accessible through the Site Offerings.</p>

          <p className="mt-4">Company does not involve itself in the agreements between Users and Third-Party Fencing Contractors or the actual provision of fence-related products and/or services in connection with the relationships created thereby.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Content; Third-Party Links</h2>
          <p>The Site contains Content which includes, but is not limited to, text, video and other information pertaining to Fence Services, as well as regularly updated Third-Party Links.</p>

          <p className="mt-4">The Content is offered for informational purposes only and is at all times subject to the disclaimers contained herein, and on the Site.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Social Media Pages</h2>
          <p>The Site contains links to the various Company Social Media Pages. The Social Media Pages are hosted and made available on third-party websites ("Social Media Websites") by third-party entities. Your use of Social Media Pages and Social Media Websites shall be governed by those Social Media Websites' applicable agreements, terms and conditions.</p>

          <p className="mt-4">You understand and agree that Company shall not be liable to you, any other User or any third-party for any claim in connection with your use of, or inability to use, the Social Media Pages and/or Social Media Websites.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Interactions</h2>
          <p>Users are solely responsible for their interactions with Third-Party Fencing Contractors. Because Company is not involved in User interactions, in the event that you have a dispute with one or more Third-Party Fencing Contractors or other Users, you hereby release Company from any and all claims, demands and/or damages (actual and consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of, or in any way connected with, such disputes.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Representations and Warranties</h2>
          <p>Each User hereby represents and warrants to Company as follows: (a) the Agreement constitutes the legal, valid and binding obligation of User which is fully enforceable against such User in accordance with its terms; (b) User understands and agrees that User has independently evaluated the desirability of utilizing the Site Offerings and that User represents that she/he has not relied on any representation and/or warranty other than those set forth in the Agreement; (c) the execution, delivery and performance of the Agreement by User will not conflict with or violate: (i) any order, judgment or decree applicable to User; or (ii) any agreement or other instrument applicable to User; and (d) the performance under this Agreement and the use of the Site Offerings will not violate any applicable laws, rules or regulations.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Indemnification</h2>
          <p>Each User agrees to indemnify, defend and hold Company, Third-Party Fencing Contractors, and their respective members, officers, directors, employees, agents, affiliates and attorneys, harmless from and against any and all liabilities, claims, actions, suits, proceedings, judgments, fines, damages, costs, losses and/or expenses (including reasonable attorneys' fees, court costs and/or settlement costs) arising from and/or related to: (a) any dispute between that User and any other User, Third-Party Fencing Contractor or third-party; (b) that User's breach of the Agreement and/or any representation or warranty contained herein; and/or (c) that User's unauthorized and/or improper use of the Site Offerings. The provisions of this Section are for the benefit of Company, its parents, subsidiaries and/or affiliates, and each of their respective Third-Party Fencing Contractors, officers, directors, members, employees, agents, shareholders, licensors, suppliers and/or attorneys. Each of these individuals and entities shall have the right to assert and enforce these provisions directly against you on its own behalf.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">License Grant</h2>
          <p>Each User is granted a non-exclusive, non-transferable, revocable and limited license to access and use the Site Offerings. Company may terminate this license at any time for any reason. Unless otherwise expressly authorized by Company, Users may only use the Site Offerings for their own personal, non-commercial use. No part of the Site Offerings may be reproduced in any form or incorporated into any information retrieval system, electronic or mechanical. No User or other third-party may use any automated means or form of scraping or data extraction to access, query or otherwise collect material from the Site Offerings except as expressly permitted by Company. No User or other third-party may use, copy, emulate, clone, rent, lease, sell, modify, decompile, disassemble, reverse engineer or transfer the Site Offerings, or any portion thereof. No User or other third-party may create any "derivative works" by altering any aspect of the Site Offerings. No User or other third-party may use the Site Offerings in conjunction with any other third-party content. No User or other third-party may exploit any aspect of the Site Offerings for any commercial purposes not expressly permitted by Company. Each User further agrees to indemnify and hold Company harmless for that User's failure to comply with this Section. Company reserves any rights not explicitly granted in the Agreement.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Proprietary Rights</h2>
          <p>The Site Offerings, as well as the organization, graphics, design, compilation, magnetic translation, digital conversion, software, services and other matters related to same, are protected under applicable copyrights, trademarks and other proprietary (including, but not limited to, intellectual property) rights. The copying, redistribution or publication by any User or other third-party of any part of the Site Offerings is strictly prohibited. No User or other third-party acquires ownership rights in or to any content, document, software, services or other materials viewed by or through the Site Offerings. The posting of information or material by and through the Site Offerings does not constitute a waiver of any right in or to such information and/or materials. The "FencesTexas" name and logo, and all associated graphics, icons and service names, are trademarks of Consumer AI. All other trademarks appearing by and through the Site Offerings are the property of their respective owners. The use of any trademark without the applicable trademark owner's express written consent is strictly prohibited.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Legal Warning</h2>
          <p>Any attempt by any individual to damage, destroy, tamper with, vandalize and/or otherwise interfere with the operation of the Site Offerings is a violation of criminal and civil law and Company will diligently pursue any and all remedies against any offending individual or entity to the fullest extent permissible by law and in equity.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Disclaimer of Warranties</h2>
          <p className="font-bold">THE SITE OFFERINGS AND ANY OTHER PRODUCTS AND/OR SERVICES OFFERED BY AND/OR THROUGH SAME ARE PROVIDED TO USERS ON AN "AS IS" AND "AS AVAILABLE" BASIS AND ALL WARRANTIES, EXPRESS AND IMPLIED, ARE DISCLAIMED TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW (INCLUDING, BUT NOT LIMITED TO, THE DISCLAIMER OF ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT OF INTELLECTUAL PROPERTY AND/OR FITNESS FOR A PARTICULAR PURPOSE). IN PARTICULAR, BUT NOT AS A LIMITATION THEREOF, COMPANY MAKES NO WARRANTY THAT THE SITE OFFERINGS AND/OR ANY OTHER PRODUCTS AND/OR SERVICES OFFERED BY AND/OR THROUGH SAME: (A) WILL MEET ANY USER'S REQUIREMENTS; (B) WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE OR THAT DEFECTS WILL BE CORRECTED; (C) WILL BE FREE OF HARMFUL COMPONENTS; (D) WILL ENABLE ANY USER TO OBTAIN FENCE-RELATED PRODUCTS AND/OR SERVICES; AND/OR (E) WILL BE ACCURATE OR RELIABLE. THE SITE OFFERINGS AND/OR ANY OTHER PRODUCTS AND/OR SERVICES OFFERED BY AND/OR THROUGH SAME MAY CONTAIN BUGS, ERRORS, PROBLEMS OR OTHER LIMITATIONS. COMPANY WILL NOT BE LIABLE FOR THE AVAILABILITY OF THE UNDERLYING INTERNET CONNECTION ASSOCIATED WITH THE SITE OFFERINGS. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY ANY USER FROM COMPANY OR OTHERWISE THROUGH OR FROM THE SITE OFFERINGS SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE AGREEMENT.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Limitation of Liability</h2>
          <p className="font-bold">EACH USER EXPRESSLY UNDERSTANDS AND AGREES THAT COMPANY SHALL NOT BE LIABLE TO THAT USER OR ANY THIRD-PARTY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL AND/OR EXEMPLARY DAMAGES INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), TO THE FULLEST EXTENT PERMISSIBLE BY LAW FOR: (A) THE USE OR INABILITY TO USE THE SITE OFFERINGS AND/OR ANY OTHER PRODUCTS AND/OR SERVICES OFFERED BY AND/OR THROUGH SAME; (B) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION, CONTENT AND/OR ANY OTHER PRODUCTS OR SERVICES PURCHASED OR OBTAINED FROM OR THROUGH THE SITE OFFERINGS; (C) ANY DISPUTE BETWEEN ANY USERS, ENTITIES, THIRD-PARTY FENCING CONTRACTORS AND/OR OTHER THIRD PARTIES; (D) THE UNAUTHORIZED ACCESS TO, OR ALTERATION OF, ANY USER DATA; (E) THE FAILURE TO OBTAIN FENCE-RELATED PRODUCTS AND/OR SERVICES; AND (F) ANY OTHER MATTER RELATING TO THE SITE OFFERINGS AND/OR ANY OTHER PRODUCTS AND/OR SERVICES OFFERED BY AND/OR THROUGH SAME. THIS LIMITATION APPLIES TO ALL CAUSES OF ACTION, IN THE AGGREGATE INCLUDING, BUT NOT LIMITED TO, BREACH OF CONTRACT, BREACH OF WARRANTY, NEGLIGENCE, STRICT LIABILITY, MISREPRESENTATION AND ANY AND ALL OTHER TORTS. EACH USER HEREBY RELEASES COMPANY FROM ANY AND ALL OBLIGATIONS, LIABILITIES AND CLAIMS IN EXCESS OF THE LIMITATIONS STATED HEREIN. IF APPLICABLE LAW DOES NOT PERMIT SUCH LIMITATIONS, THE MAXIMUM LIABILITY OF COMPANY TO ANY USER UNDER ANY AND ALL CIRCUMSTANCES WILL BE FIVE HUNDRED DOLLARS ($500.00).</p>

          <p className="mt-4 font-bold">NO ACTION, REGARDLESS OF FORM, ARISING OUT OF THE SITE OFFERINGS AND/OR ANY OTHER PRODUCTS AND/OR SERVICES OFFERED BY AND/OR THROUGH SAME, MAY BE BROUGHT BY ANY USER OR COMPANY MORE THAN ONE (1) YEAR FOLLOWING THE EVENT WHICH GAVE RISE TO THE CAUSE OF ACTION.</p>

          <p className="mt-4 font-bold">THE NEGATION OF DAMAGES SET FORTH ABOVE IS A FUNDAMENTAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN EACH USER AND COMPANY. ACCESS TO THE SITE OFFERINGS WOULD NOT BE PROVIDED TO USERS WITHOUT SUCH LIMITATIONS. SOME JURISDICTIONS DO NOT ALLOW CERTAIN LIMITATIONS ON LIABILITY AND IN SUCH JURISDICTIONS THE LIABILITY OF COMPANY SHALL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Third-Party Websites</h2>
          <p>The Site Offerings contain links to other websites on the Internet that are owned and operated by third-parties including, without limitation, the Social Media Websites, Third-Party Fencing Contractor websites and/or Third-Party Links. Company does not control the information, products or services made available on, by or through these third-party websites. The inclusion of any link does not imply endorsement by Company of the applicable website or any association with the website's operators. Because Company has no control over such websites and/or resources, each User agrees that Company is not responsible or liable for the availability or the operation of such external websites, for any material located on or available from or through any such websites or for the protection of any User's data privacy by third-parties. Each User further agrees that Company shall not be responsible or liable, directly or indirectly, for any loss or damage caused by the use of or reliance on any such material available on, by or through any such site.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Editing, Deleting and Modification</h2>
          <p>Company reserves the right in its sole discretion to edit and/or delete any documents, information or Content appearing on the Site.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Use of User Information</h2>
          <p>All material submitted by Users through or in association with the Site Offerings including, without limitation, the User Data, shall be subject to the Privacy Policy. For a copy of the Privacy Policy, please <a href="/privacy-policy" className="text-blue-600 hover:underline">click here</a>.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Dispute Resolution Provisions</h2>
          <p>The Agreement shall be treated as though it were executed and performed in Sheridan County in the State of Wyoming and shall be governed by and construed in accordance with the laws of the State of Wyoming (without regard to conflict of law principles).</p>

          <p className="mt-4">Should a dispute arise between you and either the Company or a Third-Party Fencing Contractor concerning the Site Offerings, the terms and conditions of the Agreement or the breach of same by any party hereto: (a) each party agrees to submit their dispute for resolution by arbitration before a reputable arbitration organization as mutually agreed upon by the parties, in accordance with the then current Commercial Arbitration rules of the American Arbitration Association; and (b) you agree to first commence a formal dispute proceeding by completing and submitting an Initial Dispute Notice which can be found <a href="/dispute-notice" className="text-blue-600 hover:underline">here</a>. We may choose to provide you with a final written settlement offer after receiving your Initial Dispute Notice ("Final Settlement Offer"). If we provide you with a Final Settlement Offer and you do not accept it, or we cannot otherwise satisfactorily resolve your dispute and you wish to proceed, you must submit your dispute for resolution by arbitration before a reputable arbitration organization as mutually agreed upon by the parties, in your county of residence, by filing a separate Demand for Arbitration, which is available <a href="/arbitration" className="text-blue-600 hover:underline">here</a>. For claims of Ten Thousand Dollars ($10,000.00) or less, you can choose whether the arbitration proceeds in person, by telephone or based only on submissions. If the arbitrator awards you relief that is greater than our Final Settlement Offer, then we will pay all filing, administration and arbitrator fees associated with the arbitration and, if you retained an attorney to represent you in connection with the arbitration, we will reimburse any reasonable attorneys' fees that your attorney accrued for investigating, preparing and pursuing the claim in arbitration. Any award rendered shall be final and conclusive to the parties and a judgment thereon may be entered in any court of competent jurisdiction. Nothing contained herein shall be construed to preclude any party from: (i) seeking injunctive relief in order to protect its rights pending an outcome in arbitration; and/or (ii) pursuing the matter in small claims court rather than arbitration. Although we may have a right to an award of attorneys' fees and expenses if we prevail in arbitration, we will not seek such an award from you unless the arbitrator determines that your claim was frivolous.</p>

          <p className="mt-4">To the extent permitted by law, you agree that you will not bring, join or participate in any class action lawsuit as to any claim, dispute or controversy that you may have against Company, Third-Party Fencing Contractors, and/or their respective employees, officers, directors, members, representatives and/or assigns. You agree to the entry of injunctive relief to stop such a lawsuit or to remove you as a participant in the suit. You agree to pay the attorney's fees and court costs that Company incurs in seeking such relief. This provision preventing you from bringing, joining or participating in class action lawsuits: (A) does not constitute a waiver of any of your rights or remedies to pursue a claim individually and not as a class action in binding arbitration as provided above; and (B) is an independent agreement. You may opt-out of these dispute resolution provisions by providing written notice of your decision within thirty (30) days of the date that you first access the Site.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Miscellaneous</h2>
          <p>To the extent that anything in or associated with the Site Offerings is in conflict or inconsistent with the Agreement, the Agreement shall take precedence. Company's failure to enforce any provision of the Agreement shall not be deemed a waiver of such provision nor of the right to enforce such provision. The parties do not intend that any agency or partnership relationship be created through operation of the Agreement. Should any part of the Agreement be held invalid or unenforceable, that portion shall be construed consistent with applicable law and the remaining portions shall remain in full force and effect. Company may assign its rights and obligations under the Agreement, in whole or in part, to any party at any time without notice to you. The Agreement may not, however, be assigned by you, and you may not delegate your duties under it. Headings are for reference purposes only and in no way define, limit, construe or describe the scope or extent of such section.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Contact Us</h2>
          <p>If you have any questions about the Agreement, Site Offerings or the practices of Company, you may email us as at: team@consumerai.com; or send us mail to: FencesTexas, 30 N Gould St. Ste. R, Sheridan, WY 82801.</p>
        </div>
      </main>
      
      <Footer />
    </div>
  );
} 