
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { env } from '@/lib/env';

// Create Supabase client with validated environment variables
export const supabase = createClient<Database>(
  env.VITE_SUPABASE_URL,
  env.VITE_SUPABASE_ANON_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true
    },
    global: {
      headers: {
        'x-application-name': 'fenceflow',
      },
    },
  }
);

// Add error handling function (separate function, not a property)
export const handleSupabaseError = (error: Error) => {
  console.error('Supabase Error:', error);
  // You can add error reporting service here
  return error;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
